services:
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http

  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3100/ready
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./admin_password:/run/secrets/admin_password # 如果不想用 admin 密碼，這行刪除
    environment:
      # - GF_AUTH_ANONYMOUS_ENABLED=true # 如果不想用 admin 密碼，這邊取消註解
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # 如果不想用 admin 密碼，這邊取消註解
      # - GF_AUTH_DISABLE_LOGIN_FORM=true # 如果不想用 admin 密碼，這邊取消註解
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password # 如果不想用 admin 密碼，這行刪除
    ports:
      - "3000:3000"
