global:
  scrape_interval:     15s
  evaluation_interval: 15s
  
# 想要觀測的服務都寫在這裡
scrape_configs:
  - job_name: 'prometheus' # 自我監控任務
    static_configs:
      - targets: [ 'localhost:9090' ] # 抓取自身 Prometheus 的資料
  - job_name: 'tempo' #  確認 tempo 是否有正常運作
    static_configs:
      - targets: [ 'tempo:3200' ]

  #想要觀測的話再把專案用Docker跑起來
  - job_name: 'WebApplication1'
    static_configs:
      - targets: ['webapp1:8080']

  - job_name: 'WebApplication2'
    static_configs:
      - targets: ['webapp2:8080']
