global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  #增加了一組，未來只要增加一個新的專案要觀察都要補上一個 job_name
  - job_name: 'tempo-webapi'
    static_configs:
      - targets: ['host.docker.internal:5131']
